### ISSUE TITLE
Service port mapping incorrect

### ISSUE THREAD

**Issue by ConnorJC3** [pieterlange/kube-openvpn#3]
deploy.sh has a section for the service that looks like this:

```
ports:
  - port: 1194
    protocol: ${OVPN_PROTO}
    targetPort: $OVPN_PORT
```

However, it should look like this:

```
ports:
  - port: $OVPN_PORT
    protocol: ${OVPN_PROTO}
    targetPort: 1194
```

The container always listens on port 1194 so we want to go to that port, and we want to listen on the port the user originally specified.
